import logging

logging.warning("Hello world!")

x = [(1, 2), (3, 4)]
for val in x:
    logging.exception(val)